# Generated by Django 4.1.5 on 2023-01-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='no-user.jpg', null=True, upload_to='profile/images', verbose_name='User Image'),
        ),
    ]
