# Generated by Django 4.1.5 on 2023-01-19 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Tickets', 'verbose_name_plural': 'Tickets'},
        ),
    ]
