# Generated by Django 4.1.5 on 2023-01-21 03:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0003_alter_files_created_by_alter_files_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='ImagesTicket',
        ),
        migrations.AlterModelOptions(
            name='imagesticket',
            options={'verbose_name': 'Images Ticket', 'verbose_name_plural': 'Image Tickets'},
        ),
    ]
