# Generated by Django 4.1.5 on 2023-01-21 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0005_remove_tickets_images_imagesticket_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
    ]
