# Generated by Django 4.1.5 on 2023-01-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_imagesticket_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tickets.tickets', verbose_name='Tickets'),
        ),
    ]
