# Generated by Django 4.1.5 on 2023-01-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_imagesticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='imagesticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tiket/%(id)s/images', verbose_name='Image'),
        ),
    ]
