# Generated by Django 4.1.5 on 2023-01-22 01:41

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_imagesticket_description_alter_imagesticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.tickets.models.ticketImage_directory_path, verbose_name='Image'),
        ),
    ]
