# Generated by Django 4.1.5 on 2023-01-22 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_historicalassignmenthistory_assignmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenthistory',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='previus_designee', to='tickets.tickets', verbose_name='Ticket'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassignmenthistory',
            name='ticket',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tickets.tickets', verbose_name='Ticket'),
        ),
    ]
