# Generated by Django 4.1.5 on 2023-01-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_assignmenthistory_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmenthistory',
            options={'verbose_name': 'Assignment History', 'verbose_name_plural': 'Assignments History'},
        ),
        migrations.AlterModelOptions(
            name='historicalassignmenthistory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Assignment History', 'verbose_name_plural': 'historical Assignments History'},
        ),
    ]
