# Generated by Django 4.1.5 on 2023-02-17 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_assignmenthistory_options_and_more'),
        ('comments', '0002_alter_comment_ticket_alter_historicalcomment_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.tickets', verbose_name='comments'),
        ),
    ]
